/**
 * Bank topik untuk auto-posting Job Desk (BekasiKerja.id).
 *
 * Setiap entri menghasilkan satu artikel "Tugas dan Skill" pada satu kota.
 * Publisher (publish-jobdesk-rotating.mjs) mengambil dari pool ini secara
 * bergilir dan tidak pernah memuat ulang topik yang sudah dipublikasikan.
 *
 * Field yang dibutuhkan: role, city, bunch, tugas[6], skill[6], tips[4].
 * Kota yang valid: Bekasi, Cikarang, Karawang.
 *
 * File ini hanya berisi data statis, tanpa LLM atau inferensi.
 */
export const TOPICS = [
  {
    role: "Operator Produksi",
    city: "Bekasi",
    bunch: "packing dan pengemasan",
    tugas: [
      "mengikuti instruksi mandor sebelum mulai shift",
      "memeriksa mesin pres dan komponen di sekitar sebelum bekerja",
      "mencatat hasil kerja dan kendala di akhir shift",
      "menjaga ruang produksi tetap bersih dan aman",
      "menyeahati kemasan agar tidak penyok saat ditumpuk",
      "memberi kode produksi pada setiap palet sebelum dimuat",
    ],
    skill: [
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan bahan untuk satu batch produksi",
      "menggunakan alat ukur untuk memeriksa hasil kerja",
      "menggunakan alat dengan benar dan aman",
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan kemasan untuk satu batch produksi",
    ],
    tips: [
      "pelajari area kerja sebelum mulai shift pertama",
      "gunakan alat pelindung diri sesuai jenis pekerjaan",
      "catat setiap hasil kerja agar mudah dipantau atasan",
      "tanyakan langsung ke mandor bila ada yang tidak jelas",
    ],
  },
  {
    role: "Operator Produksi",
    city: "Cikarang",
    bunch: "packing dan pengemasan",
    tugas: [
      "mengikuti instruksi mandor sebelum mulai shift",
      "memeriksa mesin pres dan komponen di sekitar sebelum bekerja",
      "mencatat hasil kerja dan kendala di akhir shift",
      "menjaga ruang produksi tetap bersih dan aman",
      "menyeahati kemasan agar tidak penyok saat ditumpuk",
      "memberi kode produksi pada setiap palet sebelum dimuat",
    ],
    skill: [
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan bahan untuk satu batch produksi",
      "menggunakan alat ukur untuk memeriksa hasil kerja",
      "menggunakan alat dengan benar dan aman",
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan kemasan untuk satu batch produksi",
    ],
    tips: [
      "pelajari area kerja sebelum mulai shift pertama",
      "gunakan alat pelindung diri sesuai jenis pekerjaan",
      "catat setiap hasil kerja agar mudah dipantau atasan",
      "tanyakan langsung ke mandor bila ada yang tidak jelas",
    ],
  },
  {
    role: "Operator Produksi",
    city: "Karawang",
    bunch: "packing dan pengemasan",
    tugas: [
      "mengikuti instruksi mandor sebelum mulai shift",
      "memeriksa mesin pres dan komponen di sekitar sebelum bekerja",
      "mencatat hasil kerja dan kendala di akhir shift",
      "menjaga ruang produksi tetap bersih dan aman",
      "menyeahati kemasan agar tidak penyok saat ditumpuk",
      "memberi kode produksi pada setiap palet sebelum dimuat",
    ],
    skill: [
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan bahan untuk satu batch produksi",
      "menggunakan alat ukur untuk memeriksa hasil kerja",
      "menggunakan alat dengan benar dan aman",
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan kemasan untuk satu batch produksi",
    ],
    tips: [
      "pelajari area kerja sebelum mulai shift pertama",
      "gunakan alat pelindung diri sesuai jenis pekerjaan",
      "catat setiap hasil kerja agar mudah dipantau atasan",
      "tanyakan langsung ke mandor bila ada yang tidak jelas",
    ],
  },
  {
    role: "Operator CNC",
    city: "Bekasi",
    bunch: "machining dan fitting",
    tugas: [
      "mengikuti instruksi operator senior sebelum mulai shift",
      "memeriksa mesin CNC dan komponen di sekitar sebelum bekerja",
      "mencatat hasil kerja dan kendala di akhir shift",
      "menjaga bengkel bubut tetap bersih dan aman",
      "mengganti tool dan melakukan preset ulang titik nol",
      "memastikan dimensi komponen sesuai gambar teknik",
    ],
    skill: [
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan bahan untuk satu batch produksi",
      "menggunakan alat ukur untuk memeriksa hasil kerja",
      "menggunakan alat dengan benar dan aman",
      "mengubah program mesin sederhana",
      "mengukur hasil machining dengan mikrometer",
    ],
    tips: [
      "pelajari area kerja sebelum mulai shift pertama",
      "gunakan alat pelindung diri sesuai jenis pekerjaan",
      "catat setiap hasil kerja agar mudah dipantau atasan",
      "tanyakan langsung ke operator senior bila ada yang tidak jelas",
    ],
  },
  {
    role: "Operator CNC",
    city: "Cikarang",
    bunch: "machining dan fitting",
    tugas: [
      "mengikuti instruksi operator senior sebelum mulai shift",
      "memeriksa mesin CNC dan komponen di sekitar sebelum bekerja",
      "mencatat hasil kerja dan kendala di akhir shift",
      "menjaga bengkel bubut tetap bersih dan aman",
      "mengganti tool dan melakukan preset ulang titik nol",
      "memastikan dimensi komponen sesuai gambar teknik",
    ],
    skill: [
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan bahan untuk satu batch produksi",
      "menggunakan alat ukur untuk memeriksa hasil kerja",
      "menggunakan alat dengan benar dan aman",
      "mengubah program mesin sederhana",
      "mengukur hasil machining dengan mikrometer",
    ],
    tips: [
      "pelajari area kerja sebelum mulai shift pertama",
      "gunakan alat pelindung diri sesuai jenis pekerjaan",
      "catat setiap hasil kerja agar mudah dipantau atasan",
      "tanyakan langsung ke operator senior bila ada yang tidak jelas",
    ],
  },
  {
    role: "Operator CNC",
    city: "Karawang",
    bunch: "machining dan fitting",
    tugas: [
      "mengikuti instruksi operator senior sebelum mulai shift",
      "memeriksa mesin CNC dan komponen di sekitar sebelum bekerja",
      "mencatat hasil kerja dan kendala di akhir shift",
      "menjaga bengkel bubut tetap bersih dan aman",
      "mengganti tool dan melakukan preset ulang titik nol",
      "memastikan dimensi komponen sesuai gambar teknik",
    ],
    skill: [
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan bahan untuk satu batch produksi",
      "menggunakan alat ukur untuk memeriksa hasil kerja",
      "menggunakan alat dengan benar dan aman",
      "mengubah program mesin sederhana",
      "mengukur hasil machining dengan mikrometer",
    ],
    tips: [
      "pelajari area kerja sebelum mulai shift pertama",
      "gunakan alat pelindung diri sesuai jenis pekerjaan",
      "catat setiap hasil kerja agar mudah dipantau atasan",
      "tanyakan langsung ke operator senior bila ada yang tidak jelas",
    ],
  },
  {
    role: "Operator Tekstil",
    city: "Bekasi",
    bunch: "jahitan dan inspeksi kain",
    tugas: [
      "mengikuti instruksi petugas QC sebelum mulai shift",
      "memeriksa mesin jahit industri dan komponen di sekitar sebelum bekerja",
      "mencatat hasil kerja dan kendala di akhir shift",
      "menjaga lantai produksi kain tetap bersih dan aman",
      "mengelas jahitan yang rontok dengan mesin pelapis",
      "mengatur ketegangan benang pada mesin jahit",
    ],
    skill: [
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan bahan untuk satu batch produksi",
      "menggunakan alat ukur untuk memeriksa hasil kerja",
      "menggunakan alat dengan benar dan aman",
      "menghitung kebutuhan benang untuk satu lot produksi",
      "memisahkan kain yang cacat sebelum dikirim",
    ],
    tips: [
      "pelajari area kerja sebelum mulai shift pertama",
      "gunakan alat pelindung diri sesuai jenis pekerjaan",
      "catat setiap hasil kerja agar mudah dipantau atasan",
      "tanyakan langsung ke petugas QC bila ada yang tidak jelas",
    ],
  },
  {
    role: "Operator Tekstil",
    city: "Cikarang",
    bunch: "jahitan dan inspeksi kain",
    tugas: [
      "mengikuti instruksi petugas QC sebelum mulai shift",
      "memeriksa mesin jahit industri dan komponen di sekitar sebelum bekerja",
      "mencatat hasil kerja dan kendala di akhir shift",
      "menjaga lantai produksi kain tetap bersih dan aman",
      "mengelas jahitan yang rontok dengan mesin pelapis",
      "mengatur ketegangan benang pada mesin jahit",
    ],
    skill: [
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan bahan untuk satu batch produksi",
      "menggunakan alat ukur untuk memeriksa hasil kerja",
      "menggunakan alat dengan benar dan aman",
      "menghitung kebutuhan benang untuk satu lot produksi",
      "memisahkan kain yang cacat sebelum dikirim",
    ],
    tips: [
      "pelajari area kerja sebelum mulai shift pertama",
      "gunakan alat pelindung diri sesuai jenis pekerjaan",
      "catat setiap hasil kerja agar mudah dipantau atasan",
      "tanyakan langsung ke petugas QC bila ada yang tidak jelas",
    ],
  },
  {
    role: "Operator Tekstil",
    city: "Karawang",
    bunch: "jahitan dan inspeksi kain",
    tugas: [
      "mengikuti instruksi petugas QC sebelum mulai shift",
      "memeriksa mesin jahit industri dan komponen di sekitar sebelum bekerja",
      "mencatat hasil kerja dan kendala di akhir shift",
      "menjaga lantai produksi kain tetap bersih dan aman",
      "mengelas jahitan yang rontok dengan mesin pelapis",
      "mengatur ketegangan benang pada mesin jahit",
    ],
    skill: [
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan bahan untuk satu batch produksi",
      "menggunakan alat ukur untuk memeriksa hasil kerja",
      "menggunakan alat dengan benar dan aman",
      "menghitung kebutuhan benang untuk satu lot produksi",
      "memisahkan kain yang cacat sebelum dikirim",
    ],
    tips: [
      "pelajari area kerja sebelum mulai shift pertama",
      "gunakan alat pelindung diri sesuai jenis pekerjaan",
      "catat setiap hasil kerja agar mudah dipantau atasan",
      "tanyakan langsung ke petugas QC bila ada yang tidak jelas",
    ],
  },
  {
    role: "Welder",
    city: "Bekasi",
    bunch: "pengelasan dan fabrikasi",
    tugas: [
      "mengikuti instruksi inspektur Mutu sebelum mulai shift",
      "memeriksa mesin las MIG atau TIG dan komponen di sekitar sebelum bekerja",
      "mencatat hasil kerja dan kendala di akhir shift",
      "menjaga bengkel pengelasan tetap bersih dan aman",
      "memotong dan membentuk profil baja dengan gerinda",
      "membaca gambar teknik hasil pengelasan",
    ],
    skill: [
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan bahan untuk satu batch produksi",
      "menggunakan alat ukur untuk memeriksa hasil kerja",
      "menggunakan alat dengan benar dan aman",
      "mengecek kekuatan las pada titik sambungan",
      "menjaga area pengelasan tetap bersih dan aman",
    ],
    tips: [
      "pelajari area kerja sebelum mulai shift pertama",
      "gunakan alat pelindung diri sesuai jenis pekerjaan",
      "catat setiap hasil kerja agar mudah dipantau atasan",
      "tanyakan langsung ke inspektur Mutu bila ada yang tidak jelas",
    ],
  },
  {
    role: "Welder",
    city: "Cikarang",
    bunch: "pengelasan dan fabrikasi",
    tugas: [
      "mengikuti instruksi inspektur Mutu sebelum mulai shift",
      "memeriksa mesin las MIG atau TIG dan komponen di sekitar sebelum bekerja",
      "mencatat hasil kerja dan kendala di akhir shift",
      "menjaga bengkel pengelasan tetap bersih dan aman",
      "memotong dan membentuk profil baja dengan gerinda",
      "membaca gambar teknik hasil pengelasan",
    ],
    skill: [
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan bahan untuk satu batch produksi",
      "menggunakan alat ukur untuk memeriksa hasil kerja",
      "menggunakan alat dengan benar dan aman",
      "mengecek kekuatan las pada titik sambungan",
      "menjaga area pengelasan tetap bersih dan aman",
    ],
    tips: [
      "pelajari area kerja sebelum mulai shift pertama",
      "gunakan alat pelindung diri sesuai jenis pekerjaan",
      "catat setiap hasil kerja agar mudah dipantau atasan",
      "tanyakan langsung ke inspektur Mutu bila ada yang tidak jelas",
    ],
  },
  {
    role: "Welder",
    city: "Karawang",
    bunch: "pengelasan dan fabrikasi",
    tugas: [
      "mengikuti instruksi inspektur Mutu sebelum mulai shift",
      "memeriksa mesin las MIG atau TIG dan komponen di sekitar sebelum bekerja",
      "mencatat hasil kerja dan kendala di akhir shift",
      "menjaga bengkel pengelasan tetap bersih dan aman",
      "memotong dan membentuk profil baja dengan gerinda",
      "membaca gambar teknik hasil pengelasan",
    ],
    skill: [
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan bahan untuk satu batch produksi",
      "menggunakan alat ukur untuk memeriksa hasil kerja",
      "menggunakan alat dengan benar dan aman",
      "mengecek kekuatan las pada titik sambungan",
      "menjaga area pengelasan tetap bersih dan aman",
    ],
    tips: [
      "pelajari area kerja sebelum mulai shift pertama",
      "gunakan alat pelindung diri sesuai jenis pekerjaan",
      "catat setiap hasil kerja agar mudah dipantau atasan",
      "tanyakan langsung ke inspektur Mutu bila ada yang tidak jelas",
    ],
  },
  {
    role: "Quality Control",
    city: "Bekasi",
    bunch: "pemeriksaan dan sortir",
    tugas: [
      "mengikuti instruksi kepala QC sebelum mulai shift",
      "memeriksa alat ukur dan komponen di sekitar sebelum bekerja",
      "mencatat hasil kerja dan kendala di akhir shift",
      "menjaga area inspeksi tetap bersih dan aman",
      "memeriksa jumlah barang pada setiap dokumen kirim",
      "menandai produk yang tidak standar untuk ditolak",
    ],
    skill: [
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan bahan untuk satu batch produksi",
      "menggunakan alat ukur untuk memeriksa hasil kerja",
      "menggunakan alat dengan benar dan aman",
      "menyusun laporan hasil pemeriksaan per hari",
      "mencatat nomor seri barang yang bermasalah",
    ],
    tips: [
      "pelajari area kerja sebelum mulai shift pertama",
      "gunakan alat pelindung diri sesuai jenis pekerjaan",
      "catat setiap hasil kerja agar mudah dipantau atasan",
      "tanyakan langsung ke kepala QC bila ada yang tidak jelas",
    ],
  },
  {
    role: "Quality Control",
    city: "Cikarang",
    bunch: "pemeriksaan dan sortir",
    tugas: [
      "mengikuti instruksi kepala QC sebelum mulai shift",
      "memeriksa alat ukur dan komponen di sekitar sebelum bekerja",
      "mencatat hasil kerja dan kendala di akhir shift",
      "menjaga area inspeksi tetap bersih dan aman",
      "memeriksa jumlah barang pada setiap dokumen kirim",
      "menandai produk yang tidak standar untuk ditolak",
    ],
    skill: [
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan bahan untuk satu batch produksi",
      "menggunakan alat ukur untuk memeriksa hasil kerja",
      "menggunakan alat dengan benar dan aman",
      "menyusun laporan hasil pemeriksaan per hari",
      "mencatat nomor seri barang yang bermasalah",
    ],
    tips: [
      "pelajari area kerja sebelum mulai shift pertama",
      "gunakan alat pelindung diri sesuai jenis pekerjaan",
      "catat setiap hasil kerja agar mudah dipantau atasan",
      "tanyakan langsung ke kepala QC bila ada yang tidak jelas",
    ],
  },
  {
    role: "Quality Control",
    city: "Karawang",
    bunch: "pemeriksaan dan sortir",
    tugas: [
      "mengikuti instruksi kepala QC sebelum mulai shift",
      "memeriksa alat ukur dan komponen di sekitar sebelum bekerja",
      "mencatat hasil kerja dan kendala di akhir shift",
      "menjaga area inspeksi tetap bersih dan aman",
      "memeriksa jumlah barang pada setiap dokumen kirim",
      "menandai produk yang tidak standar untuk ditolak",
    ],
    skill: [
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan bahan untuk satu batch produksi",
      "menggunakan alat ukur untuk memeriksa hasil kerja",
      "menggunakan alat dengan benar dan aman",
      "menyusun laporan hasil pemeriksaan per hari",
      "mencatat nomor seri barang yang bermasalah",
    ],
    tips: [
      "pelajari area kerja sebelum mulai shift pertama",
      "gunakan alat pelindung diri sesuai jenis pekerjaan",
      "catat setiap hasil kerja agar mudah dipantau atasan",
      "tanyakan langsung ke kepala QC bila ada yang tidak jelas",
    ],
  },
  {
    role: "Gudang",
    city: "Bekasi",
    bunch: "penyimpanan dan pengambilan barang",
    tugas: [
      "mengikuti instruksi kepala gudang sebelum mulai shift",
      "memeriksa forklift dan komponen di sekitar sebelum bekerja",
      "mencatat hasil kerja dan kendala di akhir shift",
      "menjaga gudang tetap bersih dan aman",
      "menerima dan memeriksa barang sesuai dokumen",
      "menyusun palet sesuai urutan pengambilan",
    ],
    skill: [
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan bahan untuk satu batch produksi",
      "menggunakan alat ukur untuk memeriksa hasil kerja",
      "menggunakan alat dengan benar dan aman",
      "mencatat barang masuk dan keluar pada sistem stok",
      "menyusun rak penyimpanan sesuai jenis barang",
    ],
    tips: [
      "pelajari area kerja sebelum mulai shift pertama",
      "gunakan alat pelindung diri sesuai jenis pekerjaan",
      "catat setiap hasil kerja agar mudah dipantau atasan",
      "tanyakan langsung ke kepala gudang bila ada yang tidak jelas",
    ],
  },
  {
    role: "Gudang",
    city: "Cikarang",
    bunch: "penyimpanan dan pengambilan barang",
    tugas: [
      "mengikuti instruksi kepala gudang sebelum mulai shift",
      "memeriksa forklift dan komponen di sekitar sebelum bekerja",
      "mencatat hasil kerja dan kendala di akhir shift",
      "menjaga gudang tetap bersih dan aman",
      "menerima dan memeriksa barang sesuai dokumen",
      "menyusun palet sesuai urutan pengambilan",
    ],
    skill: [
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan bahan untuk satu batch produksi",
      "menggunakan alat ukur untuk memeriksa hasil kerja",
      "menggunakan alat dengan benar dan aman",
      "mencatat barang masuk dan keluar pada sistem stok",
      "menyusun rak penyimpanan sesuai jenis barang",
    ],
    tips: [
      "pelajari area kerja sebelum mulai shift pertama",
      "gunakan alat pelindung diri sesuai jenis pekerjaan",
      "catat setiap hasil kerja agar mudah dipantau atasan",
      "tanyakan langsung ke kepala gudang bila ada yang tidak jelas",
    ],
  },
  {
    role: "Gudang",
    city: "Karawang",
    bunch: "penyimpanan dan pengambilan barang",
    tugas: [
      "mengikuti instruksi kepala gudang sebelum mulai shift",
      "memeriksa forklift dan komponen di sekitar sebelum bekerja",
      "mencatat hasil kerja dan kendala di akhir shift",
      "menjaga gudang tetap bersih dan aman",
      "menerima dan memeriksa barang sesuai dokumen",
      "menyusun palet sesuai urutan pengambilan",
    ],
    skill: [
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan bahan untuk satu batch produksi",
      "menggunakan alat ukur untuk memeriksa hasil kerja",
      "menggunakan alat dengan benar dan aman",
      "mencatat barang masuk dan keluar pada sistem stok",
      "menyusun rak penyimpanan sesuai jenis barang",
    ],
    tips: [
      "pelajari area kerja sebelum mulai shift pertama",
      "gunakan alat pelindung diri sesuai jenis pekerjaan",
      "catat setiap hasil kerja agar mudah dipantau atasan",
      "tanyakan langsung ke kepala gudang bila ada yang tidak jelas",
    ],
  },
  {
    role: "Teknisi Mesin",
    city: "Bekasi",
    bunch: "perawatan mesin dan pencarian kerusakan",
    tugas: [
      "mengikuti instruksi teknisi senior sebelum mulai shift",
      "memeriksa mesin produksi dan komponen di sekitar sebelum bekerja",
      "mencatat hasil kerja dan kendala di akhir shift",
      "menjaga ruang teknik tetap bersih dan aman",
      "mengganti bearing dan belt pada mesin yang macet",
      "mengukur tegangan listrik pada panel kontrol",
    ],
    skill: [
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan bahan untuk satu batch produksi",
      "menggunakan alat ukur untuk memeriksa hasil kerja",
      "menggunakan alat dengan benar dan aman",
      "mencari penyebab mesin berhenti secara bertahap",
      "melakukan uji coba sebelum mesin dijalankan kembali",
    ],
    tips: [
      "pelajari area kerja sebelum mulai shift pertama",
      "gunakan alat pelindung diri sesuai jenis pekerjaan",
      "catat setiap hasil kerja agar mudah dipantau atasan",
      "tanyakan langsung ke teknisi senior bila ada yang tidak jelas",
    ],
  },
  {
    role: "Teknisi Mesin",
    city: "Cikarang",
    bunch: "perawatan mesin dan pencarian kerusakan",
    tugas: [
      "mengikuti instruksi teknisi senior sebelum mulai shift",
      "memeriksa mesin produksi dan komponen di sekitar sebelum bekerja",
      "mencatat hasil kerja dan kendala di akhir shift",
      "menjaga ruang teknik tetap bersih dan aman",
      "mengganti bearing dan belt pada mesin yang macet",
      "mengukur tegangan listrik pada panel kontrol",
    ],
    skill: [
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan bahan untuk satu batch produksi",
      "menggunakan alat ukur untuk memeriksa hasil kerja",
      "menggunakan alat dengan benar dan aman",
      "mencari penyebab mesin berhenti secara bertahap",
      "melakukan uji coba sebelum mesin dijalankan kembali",
    ],
    tips: [
      "pelajari area kerja sebelum mulai shift pertama",
      "gunakan alat pelindung diri sesuai jenis pekerjaan",
      "catat setiap hasil kerja agar mudah dipantau atasan",
      "tanyakan langsung ke teknisi senior bila ada yang tidak jelas",
    ],
  },
  {
    role: "Teknisi Mesin",
    city: "Karawang",
    bunch: "perawatan mesin dan pencarian kerusakan",
    tugas: [
      "mengikuti instruksi teknisi senior sebelum mulai shift",
      "memeriksa mesin produksi dan komponen di sekitar sebelum bekerja",
      "mencatat hasil kerja dan kendala di akhir shift",
      "menjaga ruang teknik tetap bersih dan aman",
      "mengganti bearing dan belt pada mesin yang macet",
      "mengukur tegangan listrik pada panel kontrol",
    ],
    skill: [
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan bahan untuk satu batch produksi",
      "menggunakan alat ukur untuk memeriksa hasil kerja",
      "menggunakan alat dengan benar dan aman",
      "mencari penyebab mesin berhenti secara bertahap",
      "melakukan uji coba sebelum mesin dijalankan kembali",
    ],
    tips: [
      "pelajari area kerja sebelum mulai shift pertama",
      "gunakan alat pelindung diri sesuai jenis pekerjaan",
      "catat setiap hasil kerja agar mudah dipantau atasan",
      "tanyakan langsung ke teknisi senior bila ada yang tidak jelas",
    ],
  },
  {
    role: "Supervisor",
    city: "Bekasi",
    bunch: "pengaturan tim dan target produksi",
    tugas: [
      "mengikuti instruksi manajer plant sebelum mulai shift",
      "memeriksa sistem pencatatan produksi dan komponen di sekitar sebelum bekerja",
      "mencatat hasil kerja dan kendala di akhir shift",
      "menjaga lantai produksi tetap bersih dan aman",
      "menyusun jadwal shift dan pembagian tugas tim",
      "melaporkan capaian produksi harian ke atasan",
    ],
    skill: [
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan bahan untuk satu batch produksi",
      "menggunakan alat ukur untuk memeriksa hasil kerja",
      "menggunakan alat dengan benar dan aman",
      "mendampingi bawahan saat target tidak tercapai",
      "mencatat kendala produksi yang terjadi di lapangan",
    ],
    tips: [
      "pelajari area kerja sebelum mulai shift pertama",
      "gunakan alat pelindung diri sesuai jenis pekerjaan",
      "catat setiap hasil kerja agar mudah dipantau atasan",
      "tanyakan langsung ke manajer plant bila ada yang tidak jelas",
    ],
  },
  {
    role: "Supervisor",
    city: "Cikarang",
    bunch: "pengaturan tim dan target produksi",
    tugas: [
      "mengikuti instruksi manajer plant sebelum mulai shift",
      "memeriksa sistem pencatatan produksi dan komponen di sekitar sebelum bekerja",
      "mencatat hasil kerja dan kendala di akhir shift",
      "menjaga lantai produksi tetap bersih dan aman",
      "menyusun jadwal shift dan pembagian tugas tim",
      "melaporkan capaian produksi harian ke atasan",
    ],
    skill: [
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan bahan untuk satu batch produksi",
      "menggunakan alat ukur untuk memeriksa hasil kerja",
      "menggunakan alat dengan benar dan aman",
      "mendampingi bawahan saat target tidak tercapai",
      "mencatat kendala produksi yang terjadi di lapangan",
    ],
    tips: [
      "pelajari area kerja sebelum mulai shift pertama",
      "gunakan alat pelindung diri sesuai jenis pekerjaan",
      "catat setiap hasil kerja agar mudah dipantau atasan",
      "tanyakan langsung ke manajer plant bila ada yang tidak jelas",
    ],
  },
  {
    role: "Supervisor",
    city: "Karawang",
    bunch: "pengaturan tim dan target produksi",
    tugas: [
      "mengikuti instruksi manajer plant sebelum mulai shift",
      "memeriksa sistem pencatatan produksi dan komponen di sekitar sebelum bekerja",
      "mencatat hasil kerja dan kendala di akhir shift",
      "menjaga lantai produksi tetap bersih dan aman",
      "menyusun jadwal shift dan pembagian tugas tim",
      "melaporkan capaian produksi harian ke atasan",
    ],
    skill: [
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan bahan untuk satu batch produksi",
      "menggunakan alat ukur untuk memeriksa hasil kerja",
      "menggunakan alat dengan benar dan aman",
      "mendampingi bawahan saat target tidak tercapai",
      "mencatat kendala produksi yang terjadi di lapangan",
    ],
    tips: [
      "pelajari area kerja sebelum mulai shift pertama",
      "gunakan alat pelindung diri sesuai jenis pekerjaan",
      "catat setiap hasil kerja agar mudah dipantau atasan",
      "tanyakan langsung ke manajer plant bila ada yang tidak jelas",
    ],
  },
  {
    role: "Maintenance",
    city: "Bekasi",
    bunch: "perawatan dan perbaikan alat",
    tugas: [
      "mengikuti instruksi koordinator teknikal sebelum mulai shift",
      "memeriksa mesin dan instalasi dan komponen di sekitar sebelum bekerja",
      "mencatat hasil kerja dan kendala di akhir shift",
      "menjaga ruang maintenance tetap bersih dan aman",
      "melakukan maintenance terjadwal pada mesin",
      "mengganti komponen yang sudah aus",
    ],
    skill: [
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan bahan untuk satu batch produksi",
      "menggunakan alat ukur untuk memeriksa hasil kerja",
      "menggunakan alat dengan benar dan aman",
      "menyimpan sparepart yang sering dipakai",
      "mencatat riwayat kerusakan setiap mesin",
    ],
    tips: [
      "pelajari area kerja sebelum mulai shift pertama",
      "gunakan alat pelindung diri sesuai jenis pekerjaan",
      "catat setiap hasil kerja agar mudah dipantau atasan",
      "tanyakan langsung ke koordinator teknikal bila ada yang tidak jelas",
    ],
  },
  {
    role: "Maintenance",
    city: "Cikarang",
    bunch: "perawatan dan perbaikan alat",
    tugas: [
      "mengikuti instruksi koordinator teknikal sebelum mulai shift",
      "memeriksa mesin dan instalasi dan komponen di sekitar sebelum bekerja",
      "mencatat hasil kerja dan kendala di akhir shift",
      "menjaga ruang maintenance tetap bersih dan aman",
      "melakukan maintenance terjadwal pada mesin",
      "mengganti komponen yang sudah aus",
    ],
    skill: [
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan bahan untuk satu batch produksi",
      "menggunakan alat ukur untuk memeriksa hasil kerja",
      "menggunakan alat dengan benar dan aman",
      "menyimpan sparepart yang sering dipakai",
      "mencatat riwayat kerusakan setiap mesin",
    ],
    tips: [
      "pelajari area kerja sebelum mulai shift pertama",
      "gunakan alat pelindung diri sesuai jenis pekerjaan",
      "catat setiap hasil kerja agar mudah dipantau atasan",
      "tanyakan langsung ke koordinator teknikal bila ada yang tidak jelas",
    ],
  },
  {
    role: "Maintenance",
    city: "Karawang",
    bunch: "perawatan dan perbaikan alat",
    tugas: [
      "mengikuti instruksi koordinator teknikal sebelum mulai shift",
      "memeriksa mesin dan instalasi dan komponen di sekitar sebelum bekerja",
      "mencatat hasil kerja dan kendala di akhir shift",
      "menjaga ruang maintenance tetap bersih dan aman",
      "melakukan maintenance terjadwal pada mesin",
      "mengganti komponen yang sudah aus",
    ],
    skill: [
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan bahan untuk satu batch produksi",
      "menggunakan alat ukur untuk memeriksa hasil kerja",
      "menggunakan alat dengan benar dan aman",
      "menyimpan sparepart yang sering dipakai",
      "mencatat riwayat kerusakan setiap mesin",
    ],
    tips: [
      "pelajari area kerja sebelum mulai shift pertama",
      "gunakan alat pelindung diri sesuai jenis pekerjaan",
      "catat setiap hasil kerja agar mudah dipantau atasan",
      "tanyakan langsung ke koordinator teknikal bila ada yang tidak jelas",
    ],
  },
  {
    role: "Driver",
    city: "Bekasi",
    bunch: "pengiriman dan logistik",
    tugas: [
      "mengikuti instruksi koordinator logistik sebelum mulai shift",
      "memeriksa kendaraan operasional dan komponen di sekitar sebelum bekerja",
      "mencatat hasil kerja dan kendala di akhir shift",
      "menjaga area loading tetap bersih dan aman",
      "memeriksa kondisi kendaraan sebelum berangkat",
      "menghitung muatan agar tidak melebihi kapasitas",
    ],
    skill: [
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan bahan untuk satu batch produksi",
      "menggunakan alat ukur untuk memeriksa hasil kerja",
      "menggunakan alat dengan benar dan aman",
      "merawat kendaraan dan perangkat yang dipakai harian",
      "menyusun rute pengiriman yang paling hemat bahan bakar",
    ],
    tips: [
      "pelajari area kerja sebelum mulai shift pertama",
      "gunakan alat pelindung diri sesuai jenis pekerjaan",
      "catat setiap hasil kerja agar mudah dipantau atasan",
      "tanyakan langsung ke koordinator logistik bila ada yang tidak jelas",
    ],
  },
  {
    role: "Driver",
    city: "Cikarang",
    bunch: "pengiriman dan logistik",
    tugas: [
      "mengikuti instruksi koordinator logistik sebelum mulai shift",
      "memeriksa kendaraan operasional dan komponen di sekitar sebelum bekerja",
      "mencatat hasil kerja dan kendala di akhir shift",
      "menjaga area loading tetap bersih dan aman",
      "memeriksa kondisi kendaraan sebelum berangkat",
      "menghitung muatan agar tidak melebihi kapasitas",
    ],
    skill: [
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan bahan untuk satu batch produksi",
      "menggunakan alat ukur untuk memeriksa hasil kerja",
      "menggunakan alat dengan benar dan aman",
      "merawat kendaraan dan perangkat yang dipakai harian",
      "menyusun rute pengiriman yang paling hemat bahan bakar",
    ],
    tips: [
      "pelajari area kerja sebelum mulai shift pertama",
      "gunakan alat pelindung diri sesuai jenis pekerjaan",
      "catat setiap hasil kerja agar mudah dipantau atasan",
      "tanyakan langsung ke koordinator logistik bila ada yang tidak jelas",
    ],
  },
  {
    role: "Driver",
    city: "Karawang",
    bunch: "pengiriman dan logistik",
    tugas: [
      "mengikuti instruksi koordinator logistik sebelum mulai shift",
      "memeriksa kendaraan operasional dan komponen di sekitar sebelum bekerja",
      "mencatat hasil kerja dan kendala di akhir shift",
      "menjaga area loading tetap bersih dan aman",
      "memeriksa kondisi kendaraan sebelum berangkat",
      "menghitung muatan agar tidak melebihi kapasitas",
    ],
    skill: [
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan bahan untuk satu batch produksi",
      "menggunakan alat ukur untuk memeriksa hasil kerja",
      "menggunakan alat dengan benar dan aman",
      "merawat kendaraan dan perangkat yang dipakai harian",
      "menyusun rute pengiriman yang paling hemat bahan bakar",
    ],
    tips: [
      "pelajari area kerja sebelum mulai shift pertama",
      "gunakan alat pelindung diri sesuai jenis pekerjaan",
      "catat setiap hasil kerja agar mudah dipantau atasan",
      "tanyakan langsung ke koordinator logistik bila ada yang tidak jelas",
    ],
  },
  {
    role: "Keamanan",
    city: "Bekasi",
    bunch: "pengawasan dan akses area",
    tugas: [
      "mengikuti instruksi kepala keamanan sebelum mulai shift",
      "memeriksa sistem absen dan komponen di sekitar sebelum bekerja",
      "mencatat hasil kerja dan kendala di akhir shift",
      "menjaga pos keamanan tetap bersih dan aman",
      "memeriksa izin masuk setiap orang yang masuk area",
      "mengawasi area saat jam sepi",
    ],
    skill: [
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan bahan untuk satu batch produksi",
      "menggunakan alat ukur untuk memeriksa hasil kerja",
      "menggunakan alat dengan benar dan aman",
      "memantau lalu lintas pada pintu masuk dan keluar",
      "melaporkan kejadian tidak wajar",
    ],
    tips: [
      "pelajari area kerja sebelum mulai shift pertama",
      "gunakan alat pelindung diri sesuai jenis pekerjaan",
      "catat setiap hasil kerja agar mudah dipantau atasan",
      "tanyakan langsung ke kepala keamanan bila ada yang tidak jelas",
    ],
  },
  {
    role: "Keamanan",
    city: "Cikarang",
    bunch: "pengawasan dan akses area",
    tugas: [
      "mengikuti instruksi kepala keamanan sebelum mulai shift",
      "memeriksa sistem absen dan komponen di sekitar sebelum bekerja",
      "mencatat hasil kerja dan kendala di akhir shift",
      "menjaga pos keamanan tetap bersih dan aman",
      "memeriksa izin masuk setiap orang yang masuk area",
      "mengawasi area saat jam sepi",
    ],
    skill: [
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan bahan untuk satu batch produksi",
      "menggunakan alat ukur untuk memeriksa hasil kerja",
      "menggunakan alat dengan benar dan aman",
      "memantau lalu lintas pada pintu masuk dan keluar",
      "melaporkan kejadian tidak wajar",
    ],
    tips: [
      "pelajari area kerja sebelum mulai shift pertama",
      "gunakan alat pelindung diri sesuai jenis pekerjaan",
      "catat setiap hasil kerja agar mudah dipantau atasan",
      "tanyakan langsung ke kepala keamanan bila ada yang tidak jelas",
    ],
  },
  {
    role: "Keamanan",
    city: "Karawang",
    bunch: "pengawasan dan akses area",
    tugas: [
      "mengikuti instruksi kepala keamanan sebelum mulai shift",
      "memeriksa sistem absen dan komponen di sekitar sebelum bekerja",
      "mencatat hasil kerja dan kendala di akhir shift",
      "menjaga pos keamanan tetap bersih dan aman",
      "memeriksa izin masuk setiap orang yang masuk area",
      "mengawasi area saat jam sepi",
    ],
    skill: [
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan bahan untuk satu batch produksi",
      "menggunakan alat ukur untuk memeriksa hasil kerja",
      "menggunakan alat dengan benar dan aman",
      "memantau lalu lintas pada pintu masuk dan keluar",
      "melaporkan kejadian tidak wajar",
    ],
    tips: [
      "pelajari area kerja sebelum mulai shift pertama",
      "gunakan alat pelindung diri sesuai jenis pekerjaan",
      "catat setiap hasil kerja agar mudah dipantau atasan",
      "tanyakan langsung ke kepala keamanan bila ada yang tidak jelas",
    ],
  },
  {
    role: "Cleaning",
    city: "Bekasi",
    bunch: "pembersihan dan perawatan area",
    tugas: [
      "mengikuti instruksi koordinator housekeeping sebelum mulai shift",
      "memeriksa peralatan kebersihan dan komponen di sekitar sebelum bekerja",
      "mencatat hasil kerja dan kendala di akhir shift",
      "menjaga area produksi tetap bersih dan aman",
      "membersihkan lantai dan area makan setiap hari",
      "menyiapkan deterjen dan alat pel sesuai area",
    ],
    skill: [
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan bahan untuk satu batch produksi",
      "menggunakan alat ukur untuk memeriksa hasil kerja",
      "menggunakan alat dengan benar dan aman",
      "membuat daftar pemeriksaan kebersihan harian",
      "menyimpan alat kebersihan di tempat yang tepat",
    ],
    tips: [
      "pelajari area kerja sebelum mulai shift pertama",
      "gunakan alat pelindung diri sesuai jenis pekerjaan",
      "catat setiap hasil kerja agar mudah dipantau atasan",
      "tanyakan langsung ke koordinator housekeeping bila ada yang tidak jelas",
    ],
  },
  {
    role: "Cleaning",
    city: "Cikarang",
    bunch: "pembersihan dan perawatan area",
    tugas: [
      "mengikuti instruksi koordinator housekeeping sebelum mulai shift",
      "memeriksa peralatan kebersihan dan komponen di sekitar sebelum bekerja",
      "mencatat hasil kerja dan kendala di akhir shift",
      "menjaga area produksi tetap bersih dan aman",
      "membersihkan lantai dan area makan setiap hari",
      "menyiapkan deterjen dan alat pel sesuai area",
    ],
    skill: [
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan bahan untuk satu batch produksi",
      "menggunakan alat ukur untuk memeriksa hasil kerja",
      "menggunakan alat dengan benar dan aman",
      "membuat daftar pemeriksaan kebersihan harian",
      "menyimpan alat kebersihan di tempat yang tepat",
    ],
    tips: [
      "pelajari area kerja sebelum mulai shift pertama",
      "gunakan alat pelindung diri sesuai jenis pekerjaan",
      "catat setiap hasil kerja agar mudah dipantau atasan",
      "tanyakan langsung ke koordinator housekeeping bila ada yang tidak jelas",
    ],
  },
  {
    role: "Cleaning",
    city: "Karawang",
    bunch: "pembersihan dan perawatan area",
    tugas: [
      "mengikuti instruksi koordinator housekeeping sebelum mulai shift",
      "memeriksa peralatan kebersihan dan komponen di sekitar sebelum bekerja",
      "mencatat hasil kerja dan kendala di akhir shift",
      "menjaga area produksi tetap bersih dan aman",
      "membersihkan lantai dan area makan setiap hari",
      "menyiapkan deterjen dan alat pel sesuai area",
    ],
    skill: [
      "membaca ukuran dan spesifikasi produk dari lembar kerja",
      "menghitung kebutuhan bahan untuk satu batch produksi",
      "menggunakan alat ukur untuk memeriksa hasil kerja",
      "menggunakan alat dengan benar dan aman",
      "membuat daftar pemeriksaan kebersihan harian",
      "menyimpan alat kebersihan di tempat yang tepat",
    ],
    tips: [
      "pelajari area kerja sebelum mulai shift pertama",
      "gunakan alat pelindung diri sesuai jenis pekerjaan",
      "catat setiap hasil kerja agar mudah dipantau atasan",
      "tanyakan langsung ke koordinator housekeeping bila ada yang tidak jelas",
    ],
  },
];
